import { todayISO, tomorrowISO } from "@/lib/dates";
import { addDays, format, parseISO } from "date-fns";
import { Reservation, Service } from "@/lib/types";
import { cacheClear } from "@/lib/sheets/cache";
import { createReservation, getReservations } from "@/lib/sheets/reservations";
import { createService, getServices } from "@/lib/sheets/services";
import { ensureSpreadsheetStructure } from "@/lib/sheets/setup";

const DEMO_SERVICES: Omit<Service, "id">[] = [
  {
    name: "Airport Transfer",
    type: "Transfer",
    defaultPrice: 300,
    defaultCost: 150,
    description: "Private airport transfer between Agadir Airport and the coast.",
    active: true,
  },
  {
    name: "Timlaline Sandboarding",
    type: "Activity",
    defaultPrice: 250,
    defaultCost: 150,
    description: "Half-day sandboarding on the Timlaline dunes with hotel pickup.",
    active: true,
  },
  {
    name: "Paradise Valley",
    type: "Activity",
    defaultPrice: 400,
    defaultCost: 200,
    description: "Guided day trip to Paradise Valley pools and lunch stop.",
    active: true,
  },
  {
    name: "Private Transfer",
    type: "Transfer",
    defaultPrice: 350,
    defaultCost: 160,
    description: "Point-to-point private transfer with meet and greet.",
    active: true,
  },
  {
    name: "Agadir City Tour",
    type: "Tour",
    defaultPrice: 450,
    defaultCost: 180,
    description: "Half-day Kasbah, souk and coastline tour.",
    active: true,
  },
];

function isoFromOffset(offset: number) {
  return format(addDays(parseISO(`${todayISO()}T12:00:00`), offset), "yyyy-MM-dd");
}

export async function seedDemoData() {
  await ensureSpreadsheetStructure();

  const existingServices = await getServices();
  const byName = new Map(existingServices.map((s) => [s.name, s]));
  for (const service of DEMO_SERVICES) {
    if (!byName.has(service.name)) {
      await createService(service);
    }
  }

  const existing = await getReservations();
  const demoExists = existing.some((item) => item.bookingSource === "DEMO");
  if (demoExists) {
    return { seeded: false, message: "Demo reservations are already in the spreadsheet." };
  }

  const today = todayISO();
  const tomorrow = tomorrowISO();

  const demos: Omit<Reservation, "id" | "profit" | "createdAt" | "updatedAt">[] = [
    {
      date: today,
      time: "09:00",
      customerName: "Ahmed El Idrissi",
      phone: "+212661234567",
      whatsapp: "+212661234567",
      numberOfPeople: 2,
      type: "Transfer",
      serviceName: "Airport Transfer",
      pickupLocation: "Agadir Airport",
      destination: "Taghazout",
      price: 300,
      cost: 150,
      currency: "MAD",
      status: "Confirmed",
      paymentStatus: "Paid",
      description: "Arrival transfer after flight AT123.",
      internalNotes: "Meet at T1 arrivals with name sign.",
      driver: "Youssef",
      vehicle: "Mercedes Vito",
      flightNumber: "AT123",
      bookingSource: "DEMO",
    },
    {
      date: today,
      time: "11:30",
      customerName: "Sara Bennett",
      phone: "+447700900123",
      whatsapp: "+447700900123",
      numberOfPeople: 3,
      type: "Activity",
      serviceName: "Timlaline Sandboarding",
      pickupLocation: "Taghazout Bay",
      destination: "Timlaline Dunes",
      price: 250,
      cost: 150,
      currency: "MAD",
      status: "Confirmed",
      paymentStatus: "Deposit",
      description: "Hotel pickup for sandboarding.",
      internalNotes: "Bring extra water. Guest prefers morning start.",
      driver: "Karim",
      vehicle: "Toyota Prado",
      flightNumber: "",
      bookingSource: "DEMO",
    },
    {
      date: today,
      time: "14:00",
      customerName: "Youssef Amrani",
      phone: "+212670112233",
      whatsapp: "+212670112233",
      numberOfPeople: 4,
      type: "Activity",
      serviceName: "Paradise Valley",
      pickupLocation: "Taghazout",
      destination: "Paradise Valley",
      price: 400,
      cost: 200,
      currency: "MAD",
      status: "Pending",
      paymentStatus: "Unpaid",
      description: "Family trip to the valley pools.",
      internalNotes: "Waiting for lunch confirmation.",
      driver: "",
      vehicle: "",
      flightNumber: "",
      bookingSource: "DEMO",
    },
    {
      date: today,
      time: "16:30",
      customerName: "Fatima Zahra",
      phone: "+212661234567",
      whatsapp: "+212661234567",
      numberOfPeople: 2,
      type: "Transfer",
      serviceName: "Airport Transfer",
      pickupLocation: "Taghazout",
      destination: "Agadir Airport",
      price: 300,
      cost: 150,
      currency: "MAD",
      status: "Confirmed",
      paymentStatus: "Paid",
      description: "Departure transfer.",
      internalNotes: "Same guest as morning arrival — returning customer.",
      driver: "Youssef",
      vehicle: "Mercedes Vito",
      flightNumber: "AT456",
      bookingSource: "DEMO",
    },
    {
      date: tomorrow,
      time: "08:30",
      customerName: "Luca Rossi",
      phone: "+393331112233",
      whatsapp: "+393331112233",
      numberOfPeople: 2,
      type: "Tour",
      serviceName: "Agadir City Tour",
      pickupLocation: "Agadir Marina",
      destination: "Kasbah & Souk",
      price: 450,
      cost: 180,
      currency: "MAD",
      status: "Confirmed",
      paymentStatus: "Paid",
      description: "Half-day city tour.",
      internalNotes: "English speaking guide.",
      driver: "Hassan",
      vehicle: "Hyundai Staria",
      flightNumber: "",
      bookingSource: "DEMO",
    },
    {
      date: tomorrow,
      time: "15:00",
      customerName: "Emma Clarke",
      phone: "+447911123456",
      whatsapp: "+447911123456",
      numberOfPeople: 1,
      type: "Transfer",
      serviceName: "Private Transfer",
      pickupLocation: "Taghazout",
      destination: "Paradise Valley",
      price: 350,
      cost: 160,
      currency: "MAD",
      status: "Confirmed",
      paymentStatus: "Unpaid",
      description: "Private drop-off only.",
      internalNotes: "",
      driver: "Karim",
      vehicle: "Dacia Duster",
      flightNumber: "",
      bookingSource: "DEMO",
    },
    {
      date: isoFromOffset(3),
      time: "10:00",
      customerName: "Omar Benali",
      phone: "+212661998877",
      whatsapp: "+212661998877",
      numberOfPeople: 6,
      type: "Activity",
      serviceName: "Timlaline Sandboarding",
      pickupLocation: "Agadir Centre",
      destination: "Timlaline Dunes",
      price: 250,
      cost: 150,
      currency: "MAD",
      status: "Confirmed",
      paymentStatus: "Deposit",
      description: "Group sandboarding.",
      internalNotes: "Two extra boards requested.",
      driver: "Karim",
      vehicle: "Toyota Prado",
      flightNumber: "",
      bookingSource: "DEMO",
    },
    {
      date: isoFromOffset(-2),
      time: "13:00",
      customerName: "Nora Williams",
      phone: "+15145551212",
      whatsapp: "+15145551212",
      numberOfPeople: 2,
      type: "Activity",
      serviceName: "Paradise Valley",
      pickupLocation: "Taghazout",
      destination: "Paradise Valley",
      price: 400,
      cost: 200,
      currency: "MAD",
      status: "Completed",
      paymentStatus: "Paid",
      description: "Completed valley day trip.",
      internalNotes: "Guest loved the lunch stop.",
      driver: "Hassan",
      vehicle: "Hyundai Staria",
      flightNumber: "",
      bookingSource: "DEMO",
    },
    {
      date: isoFromOffset(-5),
      time: "07:45",
      customerName: "Ahmed El Idrissi",
      phone: "+212661234567",
      whatsapp: "+212661234567",
      numberOfPeople: 2,
      type: "Transfer",
      serviceName: "Airport Transfer",
      pickupLocation: "Agadir Airport",
      destination: "Taghazout",
      price: 300,
      cost: 150,
      currency: "MAD",
      status: "Completed",
      paymentStatus: "Paid",
      description: "Previous stay arrival.",
      internalNotes: "Repeat guest.",
      driver: "Youssef",
      vehicle: "Mercedes Vito",
      flightNumber: "AT101",
      bookingSource: "DEMO",
    },
  ];

  for (const demo of demos) {
    await createReservation({
      date: demo.date,
      time: demo.time,
      customerName: demo.customerName,
      phone: demo.phone,
      whatsapp: demo.whatsapp,
      numberOfPeople: demo.numberOfPeople,
      type: demo.type,
      serviceName: demo.serviceName,
      pickupLocation: demo.pickupLocation,
      destination: demo.destination,
      price: demo.price,
      cost: demo.cost,
      currency: demo.currency,
      status: demo.status,
      paymentStatus: demo.paymentStatus,
      description: demo.description,
      internalNotes: demo.internalNotes,
      driver: demo.driver,
      vehicle: demo.vehicle,
      flightNumber: demo.flightNumber,
      bookingSource: "DEMO",
    });
  }

  cacheClear();
  return { seeded: true, message: "Demo reservations were added to Google Sheets." };
}
